[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "llvm-args=-align-all-functions=2"
]

[build]
target = "riscv32imac-unknown-none-elf"