[package]
name = "core1"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = { workspace = true }
riscv-rt = { workspace = true }
panic-halt = { workspace = true }
udma-uart = { workspace = true }
